### PR TITLE
Shop_UI_Patch

### PR DESCRIPTION
**Pull request by whismerhill**

### CODE REVIEW

**Comment by whismerhill** [comment]
@jmhorjus
hi this is the start of working for a branch that would bring the extra side panels you had for the outfitter into a branch of its own, separating them from the rest of your PR https://github.com/endless-sky/endless-sky/pull/852 which was waaaayyy too big (hence why it didn't get included)

I know I'm copying your work here. hence why I'm trying to include you here, failing that I will try to send you an email.
I'm mainly doing this for myself.
However, if it works, if it looks fine, **if you agree**, I'd like to try & get this into the main ES project.
Thank you for any reply of yours.

**Comment by jmhorjus** [comment]
Hey, 
Good luck man. You are welcome to use any/all of the ideas/code from any branch of my ES fork with my full support. The real challenge in the ES project is getting the owner to merge anything significant that he didn't write himself. If you've read the whole 852 discussion you probably know. (if not, get some popcorn and go read it) It not the first project to suffer a similar fate either; much smaller ones have as well, though I stopped paying attention over a year ago now, so maybe things have changed. I'd still get approval from him first before investing too much of your time. I'm kinda surprised that after yet another year the shop GUI still hasn't caught up to what I have in a now 2+ year old fork. 

1.) Have you personally compiled and run the branch from 852 to see how the GUI works there?
2.) Anything new worth playing ES again for in the last year? :)

**Comment by whismerhill** [comment]
Great to hear from you,
2) to be honest I don't know because I'm kinda a recent ES player the best would be that you come to the discord & ask people.
And yes stuff sometimes is not done I know. I did a "in cargo/in stock" display PR in the outfitter a while back. it got closed pure & simple, and now in 0.9.8 the same thing exist in a very slight different form with different coding. However some PRs do make it. Honestly I think what's missing is direct communication with the lead dev so he could say what he is interested in or not.
Some of the things you had there are in though : depreciation, visual indicator icons for missing engines
cargo display (as a checkbox now or unselect all ships) ....

1) no I haven't. my aim is to keep changes at a minimum required, because if one thing is not OK it'll get rejected as a whole. And since this will be UI changes that are 100% optional, I have high hopes for integration.

the main reason is that I'm compiling in Visual Studio Community 2017 and I'm not really sure I have the will to make yet another branch to combine what's needed for your branch to work out.
And the reason I'm compiling in VSC is because there is a long standing bug that only a few of us nvidia GFX owners have. we get random TDR crashes http://developer.download.nvidia.com/NsightVisualStudio/2.2/Documentation/UserGuide/HTML/Content/Timeout_Detection_Recovery.htm that happen anytime between 10 minutes to 8+ hours after launching the game.
and after a lot of testing it seems that compiling in VSC with the win10 SDK seems to reduce the issue or nullify it, unsure yet, still in testing.

I kinda like the game hence why I launched myself in that project. Thanks a lot. come see us in discord if you wish ;)  https://discordapp.com/invite/RtBkT4C

**Comment by whismerhill** [comment]
ho and I got it compiled & partially working locally already :  http://prntscr.com/hyrj0n

**Comment by jmhorjus** [comment]
Right, I wasn't saying you should try to merge or integrate anything from 852!  Just **clone it 100% as-is**, to a new folder (or new temporary branch if you prefer) without looking at a single line of code and then **compile and run**. 

Make a new pilot (new saves would likely not work with year-old code), edit the new save file for a ton of credits, then **try out** the shop and shipyard GUIs.  Kick in the tires and see which of the changes feel good.  

Go to preferences, check "Outfit price labels" and uncheck "Details with tiles in shop". See which style you like. See which things are now redundant, and if anything inspires you. :) 

Resize the screen and watch how the different side-panels adapt on the fly. 
See how it changes to give "your ships" it's own panel apart from the currently selected one once you have enough ships.  Buy 50 sparrows, then buy 500 sparrows, then set your resolution to the max. Try parking and un-parking ships from the shipyard or outfitter. Note the color changes warning you when a ship is failing flight-check, missing a hyperdrive, or parked. Select a bunch of ships and sell all their engines, then instead of buying new engines just park them and leave the outfitter (not sure if the current main-branch can do that by now). Buy a bunch of extra outfits and put them in cargo (main branch may do that better by now, not sure).  

Then go back to your own code and re-implement the things you liked. 

That's what I meant. :)

**Pull request merged**
